### ISSUE TITLE
Admin access to new print button

### ISSUE THREAD

**Issue by quequegg** [Discordanian/mmatch#152]
For an admin:
Login (I used Amelia in MMAZ)
Start here https://az.movementmatch.org/userList.php  **_I do not see the print button._**
Click edit for any org
Then click organizations **_now I do see the print button._** at https://az.movementmatch.org/orgList.php?user_id=68

Does it seem to you that we could consolidate these two displays into one? It is confusing to me as to the difference in function and how I get to one or the other.

In any case, it would be nice to see the print button on both pages.

**Comment by alandgri** [comment]
When you are an admin, you are first seeing a list of users, because as an admin for the site, your main use case is going to be managing users.

As an admin, you can go see a list of orgs by clicking on "Organizations". The admin, in this case, sees all organizations.

When you are not an admin, you see a list of orgs tied to your user.

The organization list, for both admins and regular users, has the print button.

The user list, only seen by admins, does not have a print button because there is no user level report, and I don't think there is a need for one. The user information as it is fits all on one page.

We could change the default page for admins to orgs instead of users, but it really seems to me that the primary use case for admins is to be managing users (adding and editing).

Let me know if this makes sense.

**Comment by quequegg** [comment]
Okay, I see.  This works well.


If it turns out that I cannot get these organizations to manage their own
data, then the user V org model you created will turn out to be pivotal.
Course... it seems hard to understand what these users are doing if they
don't maintain the directory

Bob
